// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResidenceService.Api.Infrastructure.database.context;

#nullable disable

namespace ResidenceService.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506002358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Companie", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("calificacion")
                        .HasColumnType("int");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("convenio")
                        .HasColumnType("bit");

                    b.Property<string>("cp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("giro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tamañoEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanieContact", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("apellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horarioAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("idCompanie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notasAdicionales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idCompanie");

                    b.ToTable("CompanieContacts");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanyRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCompanie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProjectAssignment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdCompanie");

                    b.HasIndex("IdProjectAssignment");

                    b.ToTable("CompanyRatings");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Deliverable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormatoMuestra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deliverables");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.DeliverableAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDeliverable")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProjectAssignment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDeliverable");

                    b.HasIndex("IdProjectAssignment");

                    b.ToTable("DeliverableAssignments");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.DeliverableSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioTutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCalificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdDeliverableAssignment")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdDeliverableAssignment");

                    b.ToTable("DeliverableSubmissions");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Project", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("apoyoEconomico")
                        .HasColumnType("bit");

                    b.Property<string>("carreras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("idCompanie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("modalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("montoApoyo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroEstudiantes")
                        .HasColumnType("int");

                    b.Property<string>("periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plazosEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tecnologias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idCompanie");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.ProjectAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTutor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanieContact", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Companie", "Companie")
                        .WithMany("Contacts")
                        .HasForeignKey("idCompanie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companie");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanyRating", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Companie", "Companie")
                        .WithMany("Ratings")
                        .HasForeignKey("IdCompanie")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ResidenceService.Api.Domain.entities.ProjectAssignment", "ProjectAssignment")
                        .WithMany()
                        .HasForeignKey("IdProjectAssignment")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Companie");

                    b.Navigation("ProjectAssignment");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.DeliverableAssignment", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Deliverable", "Deliverable")
                        .WithMany("Assignments")
                        .HasForeignKey("IdDeliverable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenceService.Api.Domain.entities.ProjectAssignment", "ProjectAssignment")
                        .WithMany()
                        .HasForeignKey("IdProjectAssignment")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deliverable");

                    b.Navigation("ProjectAssignment");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.DeliverableSubmission", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.DeliverableAssignment", "DeliverableAssignment")
                        .WithMany("Submissions")
                        .HasForeignKey("IdDeliverableAssignment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliverableAssignment");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Project", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Companie", "Companie")
                        .WithMany("Projects")
                        .HasForeignKey("idCompanie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companie");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.ProjectAssignment", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Companie", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Projects");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Deliverable", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.DeliverableAssignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Project", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
