// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResidenceService.Api.Infrastructure.database.context;

#nullable disable

namespace ResidenceService.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323034430_CompleteModels")]
    partial class CompleteModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Companie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("convenio")
                        .HasColumnType("boolean");

                    b.Property<string>("cp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("giro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rfc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tamañoEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanieContact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Companieid")
                        .HasColumnType("integer");

                    b.Property<string>("apellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("apellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horarioAtencion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idCompanie")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notasAdicionales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("puesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Companieid");

                    b.ToTable("CompanieContact");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanyRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<int>("Companieid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCompanie")
                        .HasColumnType("integer");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer");

                    b.Property<int>("IdProjectAssignment")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectAssignmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Companieid");

                    b.HasIndex("ProjectAssignmentId");

                    b.ToTable("CompanyRating");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Companieid")
                        .HasColumnType("integer");

                    b.Property<bool>("apoyoEconomico")
                        .HasColumnType("boolean");

                    b.Property<string>("carreras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idCompanie")
                        .HasColumnType("integer");

                    b.Property<string>("modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("montoApoyo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreProyecto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("numeroEstudiantes")
                        .HasColumnType("integer");

                    b.Property<string>("periodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("plazosEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tecnologias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipoProyecto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Companieid");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.ProjectAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer");

                    b.Property<int>("IdProject")
                        .HasColumnType("integer");

                    b.Property<int>("IdTutor")
                        .HasColumnType("integer");

                    b.Property<int>("Projectid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Projectid");

                    b.ToTable("ProjectAssignment");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanieContact", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Companie", "Companie")
                        .WithMany("Contacts")
                        .HasForeignKey("Companieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companie");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.CompanyRating", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Companie", "Companie")
                        .WithMany("Ratings")
                        .HasForeignKey("Companieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResidenceService.Api.Domain.entities.ProjectAssignment", "ProjectAssignment")
                        .WithMany()
                        .HasForeignKey("ProjectAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companie");

                    b.Navigation("ProjectAssignment");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Project", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Companie", "Companie")
                        .WithMany("Projects")
                        .HasForeignKey("Companieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companie");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.ProjectAssignment", b =>
                {
                    b.HasOne("ResidenceService.Api.Domain.entities.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("Projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Companie", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Projects");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ResidenceService.Api.Domain.entities.Project", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
